AWS_REGION_ENV_VAR = "REGION"
TABLE_NAME_ENV_VAR = "TABLE_NAME"
HASH_KEY_NAME_ENV_VAR = "HASH_KEY_NAME"
SECONDARY_INDEX_NAME_ENV_VAR = "SECONDARY_INDEX_NAME"

ENV_VARIABLE_KEYS = [
    AWS_REGION_ENV_VAR,
    TABLE_NAME_ENV_VAR,
    HASH_KEY_NAME_ENV_VAR,
    SECONDARY_INDEX_NAME_ENV_VAR,
]
