DP_TEMP_PASSWORD_SECRET_NAME_ENV_VAR = "DP_TEMP_PASSWORD_SECRET_NAME"
DP_PASSWORD_SECRET_NAME_ENV_VAR = "DP_PASSWORD_SECRET_NAME"
DP_COGNITO_USER_POOL_ID_PARAMETER_NAME_ENV_VAR = (
    "DP_COGNITO_USER_POOL_ID_PARAMETER_NAME"
)

ENV_VARIABLE_KEYS = [
    DP_TEMP_PASSWORD_SECRET_NAME_ENV_VAR,
    DP_PASSWORD_SECRET_NAME_ENV_VAR,
    DP_COGNITO_USER_POOL_ID_PARAMETER_NAME_ENV_VAR,
]
