E2E_FINAL_REPORT_TOPIC_ARN = "E2E_FINAL_REPORT_TOPIC_ARN"
EXECUTION_RECORD_LAMBDA_NAME = "EXECUTION_RECORD_LAMBDA_NAME"
S3_REPORT_BUCKET = "S3_REPORT_BUCKET"

ENV_VARIABLE_KEYS = [
    E2E_FINAL_REPORT_TOPIC_ARN,
    EXECUTION_RECORD_LAMBDA_NAME,
    S3_REPORT_BUCKET,
]
